### ISSUE TITLE
"Get LXDE" points to Lubuntu, which does not use LXDE anymore

### ISSUE THREAD

**Issue by apandada1** [lxde/lxde.github.io#12]
The [Get LXDE](https://www.lxde.org/get/) page points users to Lubuntu, which now features LXQT. Maybe pointing to [Debian LXDE](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/) or [Fedora LDXE](https://spins.fedoraproject.org/lxde/) would be helpful for people who are not familiar with LXDE.

**Comment by nothingneko** [comment]
Fixed in #15

**Comment by jubalh** [comment]
Closed in https://github.com/lxde/lxde.github.io/pull/15

**Comment by jubalh** [comment]
Thanks @nothingneko !
