### ISSUE TITLE
Source code repository link is dead

### ISSUE THREAD

**Issue by jwilk** [lxde/lxde.github.io#14]
<https://www.lxde.org/join/> links to <https://git.lxde.org/>, but the latter server does not repond.
On IRC I was told the code is now on <https://github.com/lxde/>.
Please update the link.

**Comment by nothingneko** [comment]
Hey, I fixed this in my PR #15

**Comment by jubalh** [comment]
Closed in https://github.com/lxde/lxde.github.io/pull/15

**Comment by jubalh** [comment]
Thanks @nothingneko !
