### ISSUE TITLE
Please add Chakra to lxqt.org

### ISSUE THREAD

**Issue by s8321414** [lxde/lxde.github.io#17]
Please add Chakra to lxqt.org's distro list,I am the unofficial lxqt repo maintainer.
repo on SF: http://sourceforge.net/projects/lxqt-for-chakra/
Chakra official websit: http://chakraos.org/home/

**Comment by s8321414** [comment]
Anyone see this?

**Comment by s8321414** [comment]
:smile:

**Comment by paulolieuthier** [comment]
@s8321414, I'm sorry for that. It will be added.

**Comment by s8321414** [comment]
@paulolieuthier Ok,thx!

**Comment by paulolieuthier** [comment]
Fixes in lxde/lxde.github.io@1992219917aabc30b47d6d2b33958c67de57043d.
