### ISSUE TITLE
Download link from Fedora is wrong in the homepage of lxqt.org

### ISSUE THREAD

**Issue by tkdchen** [lxde/lxde.github.io#18]
http://download.opensuse.org/repositories/X11:/lxde:/lxqt:/fedora this is the download link from Fedora, it should be wrong I think.

**Comment by pmattern** [comment]
Fixed in the meantime.

**Comment by jubalh** [comment]
BTW Fedoras wiki sais:
> LXQt is the Qt port and the upcoming version of LXDE, the Lightweight Desktop Environment. It is the product of the merge between the LXDE-Qt and the Razor-qt projects: A lightweight, modular, blazing-fast and user-friendly desktop environment. 

I am not so sure whether this is correct. To me a port is a 1:1 copy in functionality/principles. I don't think that's the goal.
Also I doubt LXDE people will like to hear that LXQt is the upcoming version of LXDE.

Both projects are developed. They share some history, ideas and developers.

**Comment by pmattern** [comment]
[Ahem.](http://lxqt.org/about/)

**Comment by jubalh** [comment]
:-/ How often I heard complains about this

**Comment by jleclanche** [comment]
> Also I doubt LXDE people will like to hear that LXQt is the upcoming version of LXDE.

That's how the project started and it was very much its goal until there was revived interest in maintaining LXDE.

**Comment by jubalh** [comment]
Thanks @jleclanche. I opened a new bug to discuss the new text there.
