### ISSUE TITLE
about lxqt/project description

### ISSUE THREAD

**Issue by jubalh** [lxde/lxde.github.io#24]
Started in https://github.com/lxde/lxde.github.io/issues/18

I try to correct the impression that LXQt is the port/successor of LXDE in my company since some time, now I know where the impression came from :-)

Probably we should change the text in the about page.

@jleclanche explained in https://github.com/lxde/lxde.github.io/issues/18

> That's how the project started and it was very much its goal until there was revived interest in maintaining LXDE.

So probably this should be changed.
I open this bug for discussion of the new text.

**Comment by jubalh** [comment]
Maybe something like
```
LXQt is a a fusion of the LXDE-qt and razor-qt projects. It aims to create a slim modern desktop environment based on Qt. It is neither a rewrite of LXDE nor its successor.
```
Though I am not sure whether one should say so much about what is _not_.

It might be good to explain what LXQt is and in another paragraph explain its relation to LXDE.

Since I was not part of the project in during this time it might be good if someone else joins in here.

**Comment by jubalh** [comment]
Personally I also like the text from the [Arch wiki](https://wiki.archlinux.org/index.php/LXQt):

> In early 2013, Hong Jen Yee "PCMan" started porting LXDE components to Qt. The first preview of LXDE-Qt was released on July  3rd, 2013. On July 21st, it was announced that Razor-qt (a desktop similar in design to LXDE) and LXDE were merging.
> The result is LXQt, a desktop built on Qt which partly uses Razor-qt and LXDE components. While development is mainly focused on LXQt, the GTK+ 2 version of LXDE will see continued development.

**Comment by agaida** [comment]
^^ thats nice
