### ISSUE TITLE
lxqt.org domain name expires in 2016-11-25

### ISSUE THREAD

**Issue by medicalwei** [lxde/lxde.github.io#25]
As title. Consider a renewal?

**Comment by agaida** [comment]
:) - we really should.

**Comment by pmattern** [comment]
@PCMan 
According to whois the domain is registered by you. So is there any action we need to take or is some kind of automatic renewal active?

(In the long run we should probably discuss to fund stuff like this by some LXQt organization but that's a different story.)

**Comment by jleclanche** [comment]
@medicalwei @pmattern @agaida We have an organization on Gandi. @agaida you should have credentials to it; if you don't, let me know.

**Comment by agaida** [comment]
i have the credentials

**Comment by palinek** [comment]
This is done, right?

**Comment by jleclanche** [comment]
Aye
