### ISSUE TITLE
LXQt autologin possibility

### ISSUE THREAD

**Issue by szg0000** [lxde/lxde.github.io#30]
Hi!

My question is, where can I set the autologin user variable to login automatically after boot?

**Comment by pmattern** [comment]
Autologin normally isn't handled by desktop environments themselves but by display managers used to launch the sessions. So you have to refer to the documentation of the display manager you intend to use.
If it's [SDDM](https://github.com/sddm/sddm), the one recommended for LXQt, there's a GUI [sddm-config-editor](https://github.com/hagabaka/sddm-config-editor) which allows for configuring autologin as well.

That aside please note this tracker is dealing with the homepage on lxqt.org and is hence the completely wrong location. Information about reporting bugs is available in our [wiki](https://github.com/lxde/lxqt/wiki/Reporting-bugs).
