### ISSUE TITLE
Feauture: Add Favorite, Recently Used to Application Menu (plugin-menu)

### ISSUE THREAD

**Issue by ibroheem** [lxde/lxde.github.io#31]
Addition of Favorites, Recently Used to Application Menu (plugin-menu) as found in Plasma, XFCE4 (whisker menu)

**Comment by pmattern** [comment]
Duplicate of lxde/lxqt#100, also discussed in lxde/lxqt#1196.

That aside please note that this tracker is addressing the homepage lxqt.org, the panel is covered by https://github.com/lxde/lxqt/issues.

**Comment by ibroheem** [comment]
Thanks, never saw that.

**Comment by pmattern** [comment]
You're welcome.
