### ISSUE TITLE
Add rosa

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxde.github.io#4]
https://github.com/lxde/lxde-qt/issues/292

**Comment by dsilakov** [comment]
Ping? There is now an official ROSA Desktop Fresh LXQt release - http://wiki.rosalab.ru/en/index.php/Blog:ROSA_Planet/ROSA_Desktop_Fresh_R6_LXQt

**Comment by pmattern** [comment]
As already stated in lxde/lxqt#292 I'd be fine with adding ROSA Linux, too, yet some questions remain:
* What URL would you suggest an eventual link on lxqt.org should point to? The one in your previous post? Something else?
* It would be convenient if you provided a suitable image file, see the preexisting ones on https://github.com/lxde/lxde.github.io/tree/master/images. (The one proposed in lxde/lxqt#292 isn't really usable as it's not square.)
* So far I'm only aware of ISO images providing a ROSA flavour featuring LXQt. But are there any instructions how to install LXQt on a ROSA instance that's already running?   
This is targeted rather at https://github.com/lxde/lxqt/wiki where we provide instructions like this for the time being.

**Comment by dsilakov** [comment]
* Yes, let's use http://wiki.rosalab.ru/en/index.php/LXQt as an eventual link. Just now it redirects to the release notes, but I plan to improve it in the nearest future
* This one is hopefully better
![rosa](https://cloud.githubusercontent.com/assets/1215322/11763211/00daad9a-a113-11e5-9451-f79a7768227a.png)
* Yes, installing LXQt on any ROSA instance is very simple - one should simply install "task-lxqt" metapackage (we mention this in our wiki page devoted to all modern ROSA variations, see "Alternative Desktop Environments" section -  http://wiki.rosalab.ru/en/index.php/ROSA_Desktop_Fresh_R6)

**Comment by pmattern** [comment]
> Yes, let's use http://wiki.rosalab.ru/en/index.php/LXQt as [...]

Yeah, that's exactly what I had in mind. Something that's valid in the long run.

> This one is hopefully better

Err, no. It's colored and as such not helpful. Took the one from lxde/lxqt#292 and tweaked it a little.

So ROSA Linux is now mentioned both on https://github.com/lxde/lxqt/wiki and http://lxqt.org. Let us know if something's wrong.
