### ISSUE TITLE
Incorrect display panel

### ISSUE THREAD

**Issue by KaratsevN** [lxde/lxde.github.io#9]
![issue](https://user-images.githubusercontent.com/14892730/48967368-536fae00-f009-11e8-899a-840d1aac797c.png)
![issue2](https://user-images.githubusercontent.com/14892730/48967369-536fae00-f009-11e8-89a0-5ade5251cbe1.png)
Please fix this.

**Comment by medicalwei** [comment]
Hi,

For now please turn off the taskbar background. The taskbar background cannot be set as gradient but can be set as repeatable image.

Also this is the website issue tracker so you are posting in the wrong place.
